export const CHANGE_SEARCHFIELD_PENDING = "CHANGE_SEARCHFIELD_PENDING";
export const CHANGE_SEARCHFIELD_SUCCESS = "CHANGE_SEARCHFIELD_SUCCESS";
export const CHANGE_SEARCHFIELD_FAILED = "CHANGE_SEARCHFIELD_FAILED";

export const REQUEST_TOOLS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_TOOLS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_TOOLS_FAILED = "REQUEST_ROBOTS_FAILED";
